## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
#solution
import pandas as pd
dataFrame = pd.DataFrame(data)
print(dataFrame) #Q1-1
print()
print(dataFrame[((dataFrame['job']=='psychologist')|(dataFrame['job'] == 'teacher'))&(dataFrame['num_cars']>dataFrame['family_size'])]) #Q1-2
print()
print(dataFrame[(dataFrame['family_size']<=2)&(dataFrame['num_cars']>=1)]) #Q1-3
print()
print("There are " + str(len(pd.unique(dataFrame['job']))) + " unique jobs in this dataset.") #Q1-4

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

There are 4 unique jobs in this dataset.


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
#solution
dataFrame = pd.DataFrame({'fruit': fruit,'weights': weights})
print(dataFrame)
print()
meanA = np.mean((dataFrame.loc[dataFrame['fruit']=='apple','weights']))
print("The averge weight of apples is " + str("{:.1f}".format(meanA)))
meanB = np.mean((dataFrame.loc[dataFrame['fruit']=='banana','weights']))
print("The averge weight of bananas is " + str("{:.1f}".format(meanB)))
meanC = np.mean((dataFrame.loc[dataFrame['fruit']=='carrot','weights']))
print("The averge weight of carrots is " + str("{:.1f}".format(meanC)))

    fruit  weights
0  carrot      1.0
1  banana      2.0
2  banana      3.0
3   apple      4.0
4  banana      5.0
5  carrot      6.0
6   apple      7.0
7  carrot      8.0
8  banana      9.0
9  banana     10.0

The averge weight of apples is 5.5
The averge weight of bananas is 5.8
The averge weight of carrots is 5.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
#solution
print("The original array is " + str(course_name) + ".")
indices_sorted = np.argsort(course_name)
print("The indices of the sorted elements of course_name array are " + str(indices_sorted) + ".") #Q3-1
check = np.char.startswith((course_name), "P")
print("The checked result is " + str(check) + ".") #Q3-2

The original array is ['Python' 'JS' 'examples' 'PHP' 'html'].
The indices of the sorted elements of course_name array are [1 3 0 2 4].
The checked result is [ True False False  True False].


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
#solution
reversed_id = student_id[::-1]
print("The original array is " + str(student_id) + ". The reversed array is " + str(reversed_id) + ".") #Q4-1
sorted_id = np.sort(student_id)
three_largest = sorted_id[-3:]
print("The 3-largest values of the student_id array are " + ', '.join(map(str, three_largest)) + ".") #Q4-2

The original array is [1023 5202 6230 1671 1682 5241 4532]. The reversed array is [4532 5241 1682 1671 6230 5202 1023].
The 3-largest values of the student_id array are 5202, 5241, 6230.


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np
number = np.arange(1,100)
multiples = number[(number%3==0)|(number%5==0)]
print("The sum of all the multiples of 3 or 5 below 100 is " + str(multiples.sum()) + ".")

The sum of all the multiples of 3 or 5 below 100 is 2318.


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)
#solution
swapColumn = arr.copy()
swapColumn[:,[1,2]] = swapColumn[:,[2,1]]
print()
print("After swapping column 1 with column 2, the array is ")
print(str(swapColumn)) #Q6-1
swapRow = arr.copy()
swapRow[[0,1],:] = swapRow[[1,0],:]
print()
print("After swapping row 0 with row 1, the array is ")
print(str(swapRow)) #Q6-2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

After swapping column 1 with column 2, the array is 
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

After swapping row 0 with row 1, the array is 
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
